### ISSUE TITLE
Security Issues with non-logged-in user running scripts that only logged-in users should be able to run.

### ISSUE THREAD

**Issue by tjsandberg** [krcowles/ktesa#2]
1. getTitles.php is an example. It is only used when starting a new hike page, which in theory can only be run by a logged in user. But anyone could run the script by simply entering the URL. Granted, getTitles doesn't reveal anything secret, but other scripts probably do.
1. Consider adding session_start() to global_boot and doing "require_once global_boot" in every php script that contains executable code (as opposed to scripts that only contain function definitions). This should ensure that there is always one and only one session started. Therefore login and other info should always be available to any script that needs it.

**Comment by tjsandberg** [comment]
Adding comment for Ken related to #1:
Can we specify the details a bit more - e.g. is your concern that a ‘hacker' gets into our server, looks at the script names and runs them? Or looks at the js and searches for ajax calls to scripts which could be independently run?

**Comment by tjsandberg** [comment]
No, my concern is not that a hacker can "get into the server".

Yes, my concern is that a hacker can look at the js and possibly other code by doing view source or by opening the browser's development tools. Then nothing stops the hacker from running the script and seeing the output.

My Point 2 is one possible way to make sure that the user's login state is always available to any script. We would still need to check the login state in any script that should only be run by a logged-in user. It may be that the implementation details of Point 2 should be discussed on a separate thread. I included it here because I was envisioning a solution that would involve writing one or two short scripts that would be "required" at the beginning of most or all of our scripts. Those short scripts would prevent a non-logged in user from running any script that should only be run by a logged-in user.

**Comment by krcowles** [comment]
We currently check the login credentials on any script that requires access to the database - for example, someone could theoretically access the new page script, but couldn't proceed. You could not get to the list of editable hikes, you can't edit any hikes. At this point, the only thing a logged in user can do that a non-member cannot do is create/edit pages. I'm not against additional security measures, I just want to understand where they are needed and why.

**Comment by tjsandberg** [comment]
I think you inadvertently closed this. I just reopened it.

**Comment by krcowles** [comment]
Yes - apologies, I did inadvertently close the issue. Thanks for reopening. Adding session_start to global_boot, and 'require_once global_boot.php' in a script could enable login checking within the script. While there are a good number of scripts already requiring login (e.g. to access the data base), perhaps a function (e.g. verifyLogin()) could be added to provide something like a 'die' statement with a warning message on an otherwise blank page. There are a number of scripts which can be accessed by anyone (home.php, tableOnly.php, etc) and should not contain the verification step. Perhaps the first step is to identify scripts requiring (or not requiring) login verification.

**Comment by krcowles** [comment]
After re-reading the concern about finding php script names in the js or source code, I have re-examined the issue. Since the server always processes php prior to sending the html back to the client, the only place someone could see a php script name is in the js - as ajax calls (jQuery or XMLHttpRequest), never in the html itself. Given that, I have re-examined all of those scripts and am sending you the results in a spreadsheet via email. I will protect the susceptible scripts after you have had time to review, and comment if you wish.

**Comment by krcowles** [comment]
Access control has been reviewed offline, and the branch appears to be working. A rebased branch (issue2RB) has been created, pushed, then merged to master (also pushed). A test site exists for this commit: [https://nmhikes.com/master_36153ac](url). The test database has been specified.

**Comment by krcowles** [comment]
Test site moved to main. Pull request closed.
